export enum GeneralView {
  REDIRECT = 'REDIRECT',
  AUTHENTICATION = 'AUTHENTICATION',
  USER = 'USER',
  ERROR = 'ERROR',
}

export enum AuthenticationView {
  AUTHENTICATION_LOGIN = 'AUTHENTICATION_LOGIN',
  AUTHENTICATION_REGISTRATION = 'AUTHENTICATION_REGISTRATION',
  AUTHENTICATION_FORGOT_PASSWORD = 'AUTHENTICATION_FORGOT_PASSWORD',
}

export enum UserView {
  USER_CONTRACTS = 'USER_CONTRACTS',
  USER_INVESTMENT = 'USER_INVESTMENT',
  USER_PARTNERS = 'USER_PARTNERS',
  USER_HISTORY = 'USER_HISTORY',
  USER_PROFILE = 'USER_PROFILE',
}

export enum ErrorView {
  ERROR_404 = 'ERROR_404',
}
